/*
 * Decompiled with CFR 0.0.
 * 
 * Could not load the following classes:
 *  java.lang.Object
 *  java.lang.String
 *  java.util.Objects
 *  org.bouncycastle.asn1.ASN1ObjectIdentifier
 */
package org.bouncycastle.asn1.x9;

import java.util.Objects;
import org.bouncycastle.asn1.ASN1ObjectIdentifier;

public interface X9ObjectIdentifiers {
    public static final ASN1ObjectIdentifier ansi_X9_42;
    public static final ASN1ObjectIdentifier ansi_X9_62;
    public static final ASN1ObjectIdentifier c2pnb163v1;
    public static final ASN1ObjectIdentifier c2pnb163v2;
    public static final ASN1ObjectIdentifier c2pnb163v3;
    public static final ASN1ObjectIdentifier c2pnb176w1;
    public static final ASN1ObjectIdentifier c2pnb208w1;
    public static final ASN1ObjectIdentifier c2pnb272w1;
    public static final ASN1ObjectIdentifier c2pnb304w1;
    public static final ASN1ObjectIdentifier c2pnb368w1;
    public static final ASN1ObjectIdentifier c2tnb191v1;
    public static final ASN1ObjectIdentifier c2tnb191v2;
    public static final ASN1ObjectIdentifier c2tnb191v3;
    public static final ASN1ObjectIdentifier c2tnb239v1;
    public static final ASN1ObjectIdentifier c2tnb239v2;
    public static final ASN1ObjectIdentifier c2tnb239v3;
    public static final ASN1ObjectIdentifier c2tnb359v1;
    public static final ASN1ObjectIdentifier c2tnb431r1;
    public static final ASN1ObjectIdentifier cTwoCurve;
    public static final ASN1ObjectIdentifier characteristic_two_field;
    public static final ASN1ObjectIdentifier dhSinglePass_cofactorDH_sha1kdf_scheme;
    public static final ASN1ObjectIdentifier dhSinglePass_stdDH_sha1kdf_scheme;
    public static final ASN1ObjectIdentifier ecdsa_with_SHA2;
    public static final ASN1ObjectIdentifier ecdsa_with_SHA224;
    public static final ASN1ObjectIdentifier ecdsa_with_SHA256;
    public static final ASN1ObjectIdentifier ecdsa_with_SHA384;
    public static final ASN1ObjectIdentifier ecdsa_with_SHA512;
    public static final ASN1ObjectIdentifier ellipticCurve;
    public static final ASN1ObjectIdentifier id_ecPublicKey;
    public static final ASN1ObjectIdentifier id_ecSigType;
    public static final ASN1ObjectIdentifier id_fieldType;
    public static final ASN1ObjectIdentifier id_publicKeyType;
    public static final ASN1ObjectIdentifier mqvSinglePass_sha1kdf_scheme;
    public static final ASN1ObjectIdentifier ppBasis;
    public static final ASN1ObjectIdentifier prime192v1;
    public static final ASN1ObjectIdentifier prime192v2;
    public static final ASN1ObjectIdentifier prime192v3;
    public static final ASN1ObjectIdentifier prime239v1;
    public static final ASN1ObjectIdentifier prime239v2;
    public static final ASN1ObjectIdentifier prime239v3;
    public static final ASN1ObjectIdentifier prime256v1;
    public static final ASN1ObjectIdentifier primeCurve;
    public static final ASN1ObjectIdentifier prime_field;
    public static final ASN1ObjectIdentifier tpBasis;
    public static final ASN1ObjectIdentifier x9_42_schemes;
    public static final ASN1ObjectIdentifier x9_44;
    public static final ASN1ObjectIdentifier x9_44_components;
    public static final ASN1ObjectIdentifier x9_63_scheme;

    public static {
        ASN1ObjectIdentifier aSN1ObjectIdentifier;
        ASN1ObjectIdentifier aSN1ObjectIdentifier2;
        ASN1ObjectIdentifier aSN1ObjectIdentifier3;
        ASN1ObjectIdentifier aSN1ObjectIdentifier4;
        ASN1ObjectIdentifier aSN1ObjectIdentifier5;
        ASN1ObjectIdentifier aSN1ObjectIdentifier6;
        ASN1ObjectIdentifier aSN1ObjectIdentifier7;
        ASN1ObjectIdentifier aSN1ObjectIdentifier8;
        ASN1ObjectIdentifier aSN1ObjectIdentifier9;
        ASN1ObjectIdentifier aSN1ObjectIdentifier10;
        ASN1ObjectIdentifier aSN1ObjectIdentifier11;
        ASN1ObjectIdentifier aSN1ObjectIdentifier12;
        ASN1ObjectIdentifier aSN1ObjectIdentifier13;
        ASN1ObjectIdentifier aSN1ObjectIdentifier14;
        ansi_X9_62 = aSN1ObjectIdentifier14 = new ASN1ObjectIdentifier("1.2.840.10045");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier14);
        id_fieldType = aSN1ObjectIdentifier10 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier14, "1");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier10);
        prime_field = new ASN1ObjectIdentifier(aSN1ObjectIdentifier10, "1");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier10);
        characteristic_two_field = aSN1ObjectIdentifier9 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier10, "2");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier9);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier9, "3.1");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier9);
        tpBasis = new ASN1ObjectIdentifier(aSN1ObjectIdentifier9, "3.2");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier9);
        ppBasis = new ASN1ObjectIdentifier(aSN1ObjectIdentifier9, "3.3");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier14);
        id_ecSigType = aSN1ObjectIdentifier5 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier14, "4");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier5);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier5, "1");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier14);
        id_publicKeyType = aSN1ObjectIdentifier13 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier14, "2");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier13);
        id_ecPublicKey = new ASN1ObjectIdentifier(aSN1ObjectIdentifier13, "1");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier5);
        ecdsa_with_SHA2 = aSN1ObjectIdentifier3 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier5, "3");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier3);
        ecdsa_with_SHA224 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier3, "1");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier3);
        ecdsa_with_SHA256 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier3, "2");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier3);
        ecdsa_with_SHA384 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier3, "3");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier3);
        ecdsa_with_SHA512 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier3, "4");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier14);
        ellipticCurve = aSN1ObjectIdentifier = new ASN1ObjectIdentifier(aSN1ObjectIdentifier14, "3");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier);
        cTwoCurve = aSN1ObjectIdentifier6 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier, "0");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier6);
        c2pnb163v1 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "1");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier6);
        c2pnb163v2 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "2");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier6);
        c2pnb163v3 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "3");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier6);
        c2pnb176w1 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "4");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier6);
        c2tnb191v1 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "5");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier6);
        c2tnb191v2 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "6");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier6);
        c2tnb191v3 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "7");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier6);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "8");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier6);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "9");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier6);
        c2pnb208w1 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "10");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier6);
        c2tnb239v1 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "11");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier6);
        c2tnb239v2 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "12");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier6);
        c2tnb239v3 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "13");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier6);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "14");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier6);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "15");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier6);
        c2pnb272w1 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "16");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier6);
        c2pnb304w1 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "17");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier6);
        c2tnb359v1 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "18");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier6);
        c2pnb368w1 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "19");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier6);
        c2tnb431r1 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "20");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier);
        primeCurve = aSN1ObjectIdentifier7 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier, "1");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier7);
        prime192v1 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier7, "1");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier7);
        prime192v2 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier7, "2");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier7);
        prime192v3 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier7, "3");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier7);
        prime239v1 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier7, "4");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier7);
        prime239v2 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier7, "5");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier7);
        prime239v3 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier7, "6");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier7);
        prime256v1 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier7, "7");
        new ASN1ObjectIdentifier("1.2.840.10040.4.1");
        new ASN1ObjectIdentifier("1.2.840.10040.4.3");
        x9_63_scheme = aSN1ObjectIdentifier4 = new ASN1ObjectIdentifier("1.3.133.16.840.63.0");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier4);
        dhSinglePass_stdDH_sha1kdf_scheme = new ASN1ObjectIdentifier(aSN1ObjectIdentifier4, "2");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier4);
        dhSinglePass_cofactorDH_sha1kdf_scheme = new ASN1ObjectIdentifier(aSN1ObjectIdentifier4, "3");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier4);
        mqvSinglePass_sha1kdf_scheme = new ASN1ObjectIdentifier(aSN1ObjectIdentifier4, "16");
        ansi_X9_42 = aSN1ObjectIdentifier12 = new ASN1ObjectIdentifier("1.2.840.10046");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier12);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "2.1");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier12);
        x9_42_schemes = aSN1ObjectIdentifier11 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "3");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier11);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier11, "1");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier11);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier11, "2");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier11);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier11, "3");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier11);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier11, "4");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier11);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier11, "5");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier11);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier11, "6");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier11);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier11, "7");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier11);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier11, "8");
        x9_44 = aSN1ObjectIdentifier2 = new ASN1ObjectIdentifier("1.3.133.16.840.9.44");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier2);
        x9_44_components = aSN1ObjectIdentifier8 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier2, "1");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier8);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier8, "1");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier8);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier8, "2");
    }
}

