/*
 * Decompiled with CFR 0.0.
 * 
 * Could not load the following classes:
 *  java.lang.Object
 *  java.lang.String
 *  java.util.Objects
 *  org.bouncycastle.asn1.ASN1ObjectIdentifier
 */
package org.bouncycastle.asn1.pkcs;

import java.util.Objects;
import org.bouncycastle.asn1.ASN1ObjectIdentifier;

public interface PKCSObjectIdentifiers {
    public static final ASN1ObjectIdentifier bagtypes;
    public static final ASN1ObjectIdentifier certTypes;
    public static final ASN1ObjectIdentifier crlTypes;
    public static final ASN1ObjectIdentifier digestAlgorithm;
    public static final ASN1ObjectIdentifier encryptionAlgorithm;
    public static final ASN1ObjectIdentifier id_aa;
    public static final ASN1ObjectIdentifier id_aa_ets_commitmentType;
    public static final ASN1ObjectIdentifier id_aa_ets_otherSigCert;
    public static final ASN1ObjectIdentifier id_aa_ets_sigPolicyId;
    public static final ASN1ObjectIdentifier id_aa_ets_signerLocation;
    public static final ASN1ObjectIdentifier id_alg;
    public static final ASN1ObjectIdentifier id_alg_hss_lms_hashsig;
    public static final ASN1ObjectIdentifier id_ct;
    public static final ASN1ObjectIdentifier id_cti;
    public static final ASN1ObjectIdentifier id_smime;
    public static final ASN1ObjectIdentifier pkcs_1;
    public static final ASN1ObjectIdentifier pkcs_12;
    public static final ASN1ObjectIdentifier pkcs_12PbeIds;
    public static final ASN1ObjectIdentifier pkcs_3;
    public static final ASN1ObjectIdentifier pkcs_5;
    public static final ASN1ObjectIdentifier pkcs_9;

    public static {
        ASN1ObjectIdentifier aSN1ObjectIdentifier;
        ASN1ObjectIdentifier aSN1ObjectIdentifier2;
        ASN1ObjectIdentifier aSN1ObjectIdentifier3;
        ASN1ObjectIdentifier aSN1ObjectIdentifier4;
        ASN1ObjectIdentifier aSN1ObjectIdentifier5;
        ASN1ObjectIdentifier aSN1ObjectIdentifier6;
        ASN1ObjectIdentifier aSN1ObjectIdentifier7;
        ASN1ObjectIdentifier aSN1ObjectIdentifier8;
        ASN1ObjectIdentifier aSN1ObjectIdentifier9;
        ASN1ObjectIdentifier aSN1ObjectIdentifier10;
        ASN1ObjectIdentifier aSN1ObjectIdentifier11;
        ASN1ObjectIdentifier aSN1ObjectIdentifier12;
        ASN1ObjectIdentifier aSN1ObjectIdentifier13;
        ASN1ObjectIdentifier aSN1ObjectIdentifier14;
        ASN1ObjectIdentifier aSN1ObjectIdentifier15;
        ASN1ObjectIdentifier aSN1ObjectIdentifier16;
        pkcs_1 = aSN1ObjectIdentifier16 = new ASN1ObjectIdentifier("1.2.840.113549.1.1");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier16);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier16, "1");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier16);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier16, "2");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier16);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier16, "3");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier16);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier16, "4");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier16);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier16, "5");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier16);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier16, "6");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier16);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier16, "7");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier16);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier16, "8");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier16);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier16, "9");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier16);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier16, "10");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier16);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier16, "11");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier16);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier16, "12");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier16);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier16, "13");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier16);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier16, "14");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier16);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier16, "15");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier16);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier16, "16");
        pkcs_3 = aSN1ObjectIdentifier11 = new ASN1ObjectIdentifier("1.2.840.113549.1.3");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier11);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier11, "1");
        pkcs_5 = aSN1ObjectIdentifier9 = new ASN1ObjectIdentifier("1.2.840.113549.1.5");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier9);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier9, "1");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier9);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier9, "4");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier9);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier9, "3");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier9);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier9, "6");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier9);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier9, "10");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier9);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier9, "11");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier9);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier9, "13");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier9);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier9, "12");
        encryptionAlgorithm = aSN1ObjectIdentifier3 = new ASN1ObjectIdentifier("1.2.840.113549.3");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier3);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier3, "7");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier3);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier3, "2");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier3);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier3, "4");
        digestAlgorithm = aSN1ObjectIdentifier7 = new ASN1ObjectIdentifier("1.2.840.113549.2");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier7);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier7, "2");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier7);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier7, "4");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier7);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier7, "5");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier7);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier7, "7").intern();
        Objects.requireNonNull((Object)aSN1ObjectIdentifier7);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier7, "8").intern();
        Objects.requireNonNull((Object)aSN1ObjectIdentifier7);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier7, "9").intern();
        Objects.requireNonNull((Object)aSN1ObjectIdentifier7);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier7, "10").intern();
        Objects.requireNonNull((Object)aSN1ObjectIdentifier7);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier7, "11").intern();
        new ASN1ObjectIdentifier("1.2.840.113549.1.7").intern();
        new ASN1ObjectIdentifier("1.2.840.113549.1.7.1").intern();
        new ASN1ObjectIdentifier("1.2.840.113549.1.7.2").intern();
        new ASN1ObjectIdentifier("1.2.840.113549.1.7.3").intern();
        new ASN1ObjectIdentifier("1.2.840.113549.1.7.4").intern();
        new ASN1ObjectIdentifier("1.2.840.113549.1.7.5").intern();
        new ASN1ObjectIdentifier("1.2.840.113549.1.7.6").intern();
        pkcs_9 = aSN1ObjectIdentifier5 = new ASN1ObjectIdentifier("1.2.840.113549.1.9");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier5);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier5, "1").intern();
        Objects.requireNonNull((Object)aSN1ObjectIdentifier5);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier5, "2").intern();
        Objects.requireNonNull((Object)aSN1ObjectIdentifier5);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier5, "3").intern();
        Objects.requireNonNull((Object)aSN1ObjectIdentifier5);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier5, "4").intern();
        Objects.requireNonNull((Object)aSN1ObjectIdentifier5);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier5, "5").intern();
        Objects.requireNonNull((Object)aSN1ObjectIdentifier5);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier5, "6").intern();
        Objects.requireNonNull((Object)aSN1ObjectIdentifier5);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier5, "7").intern();
        Objects.requireNonNull((Object)aSN1ObjectIdentifier5);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier5, "8").intern();
        Objects.requireNonNull((Object)aSN1ObjectIdentifier5);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier5, "9").intern();
        Objects.requireNonNull((Object)aSN1ObjectIdentifier5);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier5, "13").intern();
        Objects.requireNonNull((Object)aSN1ObjectIdentifier5);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier5, "14").intern();
        Objects.requireNonNull((Object)aSN1ObjectIdentifier5);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier5, "15").intern();
        Objects.requireNonNull((Object)aSN1ObjectIdentifier5);
        id_smime = aSN1ObjectIdentifier13 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier5, "16").intern();
        Objects.requireNonNull((Object)aSN1ObjectIdentifier5);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier5, "20").intern();
        Objects.requireNonNull((Object)aSN1ObjectIdentifier5);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier5, "21").intern();
        Objects.requireNonNull((Object)aSN1ObjectIdentifier5);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier5, "22.1");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier5);
        certTypes = aSN1ObjectIdentifier14 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier5, "22");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier14);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier14, "1").intern();
        Objects.requireNonNull((Object)aSN1ObjectIdentifier14);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier14, "2").intern();
        Objects.requireNonNull((Object)aSN1ObjectIdentifier5);
        crlTypes = aSN1ObjectIdentifier12 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier5, "23");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier12);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier12, "1").intern();
        Objects.requireNonNull((Object)aSN1ObjectIdentifier5);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier5, "52").intern();
        Objects.requireNonNull((Object)aSN1ObjectIdentifier5);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier5, "15.1");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier5);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier5, "15.2");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier5);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier5, "15.3");
        id_ct = aSN1ObjectIdentifier6 = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.1");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier6);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "2");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier6);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "4");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier6);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "9");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier6);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "23");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier6);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier6, "31");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier13);
        id_alg = aSN1ObjectIdentifier = new ASN1ObjectIdentifier(aSN1ObjectIdentifier13, "3");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier, "9");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier, "14");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier);
        id_alg_hss_lms_hashsig = new ASN1ObjectIdentifier(aSN1ObjectIdentifier, "17");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier, "18");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier, "28");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier, "29");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier, "30");
        id_cti = aSN1ObjectIdentifier10 = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.6");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier10);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier10, "1");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier10);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier10, "2");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier10);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier10, "3");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier10);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier10, "4");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier10);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier10, "5");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier10);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier10, "6");
        id_aa = aSN1ObjectIdentifier2 = new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.2");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier2);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier2, "1");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier2);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier2, "4");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier2);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier2, "5");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier2);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier2, "10");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier2);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier2, "11");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier2);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier2, "12");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier2);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier2, "47");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier2);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier2, "7");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier2);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier2, "14");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier2);
        id_aa_ets_sigPolicyId = new ASN1ObjectIdentifier(aSN1ObjectIdentifier2, "15");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier2);
        id_aa_ets_commitmentType = new ASN1ObjectIdentifier(aSN1ObjectIdentifier2, "16");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier2);
        id_aa_ets_signerLocation = new ASN1ObjectIdentifier(aSN1ObjectIdentifier2, "17");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier2);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier2, "18");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier2);
        id_aa_ets_otherSigCert = new ASN1ObjectIdentifier(aSN1ObjectIdentifier2, "19");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier2);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier2, "20");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier2);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier2, "21");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier2);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier2, "22");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier2);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier2, "23");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier2);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier2, "24");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier2);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier2, "25");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier2);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier2, "26");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier2);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier2, "27");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier2);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier2, "37");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier2);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier2, "38");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier2);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier2, "54");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier2);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier2, "43");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier2);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier2, "40");
        new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.5.1");
        new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.5.2");
        pkcs_12 = aSN1ObjectIdentifier4 = new ASN1ObjectIdentifier("1.2.840.113549.1.12");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier4);
        bagtypes = aSN1ObjectIdentifier8 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier4, "10.1");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier8);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier8, "1");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier8);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier8, "2");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier8);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier8, "3");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier8);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier8, "4");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier8);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier8, "5");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier8);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier8, "6");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier4);
        pkcs_12PbeIds = aSN1ObjectIdentifier15 = new ASN1ObjectIdentifier(aSN1ObjectIdentifier4, "1");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier15);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier15, "1");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier15);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier15, "2");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier15);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier15, "3");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier15);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier15, "4");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier15);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier15, "5");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier15);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier15, "6");
        Objects.requireNonNull((Object)aSN1ObjectIdentifier15);
        new ASN1ObjectIdentifier(aSN1ObjectIdentifier15, "6");
        new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.3.6");
        new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.3.7");
        new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.3.5");
        new ASN1ObjectIdentifier("1.2.840.113549.1.9.16.3.10");
    }
}

